version: '3.8'

services:
  neo4j:
    image: neo4j:5.13
    container_name: learning_neo4j
    environment:
      - NEO4J_AUTH=neo4j/learningplatform123
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    ports:
      - "7474:7474"  # Neo4j Browser
      - "7687:7687"  # Bolt protocol
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - learning_network
    restart: unless-stopped

  web:
    build: .
    container_name: learning_web
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=learningplatform123
      - FLASK_SECRET_KEY=change-this-in-production
      - FLASK_DEBUG=False
    ports:
      - "5000:5000"
    depends_on:
      - neo4j
    networks:
      - learning_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  neo4j_data:
  neo4j_logs:

networks:
  learning_network:
    driver: bridge
